version: "3.5"

services:

  engine-web:
    container_name: engine-web
    build:
      context: ${engine_path_host}
      dockerfile: engine-nginx.dockerfile
    restart: unless-stopped
    ports:
      - 8043:80
    volumes:
      - ${engine_path_host}:${engine_path_container}
    links:
      - engine-php
    tty: true

  engine-php:
    container_name: engine-php
    build:
      context: ${engine_path_host}
      dockerfile: engine-php.dockerfile
    restart: unless-stopped
    volumes:
      - ${engine_path_host}:${engine_path_container}
    working_dir: ${engine_path_container}
    links:
      - url_db
      - cache
    tty: true

      
  url_db:
    container_name: url_db
    image: mariadb:10.6.4
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=42
      - MARIADB_DATABASE=url
      - MARIADB_USER=url
      - MARIADB_PASSWORD=8kr659skY5EZM
    volumes:
      - ${back_db_path_host}:/var/lib/mysql
    tty: true

  # db:
  #   container_name: db
  #   image: mariadb:10.6.4
  #   restart: unless-stopped
  #   environment:
  #     - MARIADB_ROOT_PASSWORD=42
  #     - MARIADB_DATABASE=db
  #     - MARIADB_USER=db-user
  #     - MARIADB_PASSWORD=8kr659skY5EZM
  #   volumes:
  #     - ${back_db_path_host}:/var/lib/mysql
  #   tty: true

  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8077:8080
    links:
      - url_db
    tty: true

  cache:
    container_name: cache
    image: redis:6.2.6
    restart: unless-stopped
    tty: true

  composer-engine:
    container_name: composer-engine
    image: composer:2.2.4
    restart: 'no'
    volumes:
      - ${engine_path_host}:${engine_path_container}
    working_dir: ${engine_path_container}
    command: update